company/urls.py
from django.conf.urls import url
from company import views as company_views
from . import views

app_name = 'company'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add/$', views.AddView.as_view(), name='company_add'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='company_detail'),
    url(r'^detail/(?P<pk>[0-9]+)/edit/$', views.CompanyEdit.as_view(), name='company_edit'),
    url(r'^detail/(?P<pk>[0-9]+)/delete/$', views.CompanyDelete.as_view(), name='company_delete'),
    url(r'^tree/$', company_views.show_companies, name='company_tree'),
]

test_companies/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('company.urls', namespace='company')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

company_estimated_earnings = ['earnings']

class Company(MPTTModel):
    name = models.CharField(max_length=50, null=True)
    earnings = models.DecimalField(max_digits=8, decimal_places=2, null=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='childrens', db_index=True, on_delete=models.CASCADE)

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'

    def __str__(self):
        return self.name

    def get_all_children(self, include_self=True):
        r = []
        if include_self:
            r.append(self)
        for c in Company.objects.filter(parent=self):
            _r = c.get_all_children(include_self=True)
            if 0 < len(_r):
                r.extend(_r)
        return r

    @property
    def count_earnings(self):
        company_earnings = self.get_all_children()
        total_company_estimated_earnings = 0
        for comp in company_earnings:
            total_company_estimated_earnings += comp.earnings
        return total_company_estimated_earnings

company/forms.py
from .models import Company
from django import forms

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name', 'earnings', 'parent']

company/views.py
from django.views import generic
from .forms import CompanyForm
from django.db.models import Sum
from company.models import Company
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render

class IndexView(generic.ListView):
    template_name = 'company/index.html'
    context_object_name = 'company_list'


    def get_queryset(self):
        return Company.objects.all()


class AddView(generic.CreateView):
    template_name = 'company/add.html'
    model = Company
    form_class = CompanyForm
    success_url = reverse_lazy('company:index')

class DetailView(generic.DetailView):
    model = Company
    template_name = 'company/detail.html'

class CompanyEdit(generic.UpdateView):
    model = Company
    success_url = reverse_lazy('company:index')
    form_class = CompanyForm


class CompanyDelete(generic.DeleteView):
    model = Company
    success_url = reverse_lazy('company:index')

def show_companies(request):
    return render(request, 'company/tree.html', {'nodes':Company.objects.all()})

company/templates/company/add.html
{% extends 'company/base.html' %}
{% block title %}
Add
{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add new Company</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'company/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>


                            </div>

                        </div>
                    </form>

                </div>
            </div>


        </div>


    </div>
</div>
{% endblock %}

company/templates/company/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Belyi{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'company:index' %}">
                 <span class="navbar-brand glyphicon glyphicon-home" ></span>
                </a>
            </div>

            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'company:company_add' %}">
                            <span class="" aria-hidden="true"></span>&nbsp; Add Company
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'company:company_tree' %}">
                            <span class="" aria-hidden="true"></span>&nbsp; Tree
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

company/templates/company/company_form.html
{% extends 'company/base.html' %}
{% block title %}Edit{% endblock %}
{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Edit Company Inform</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'company/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>

                        </div>
                    </form>

                </div>
            </div>


        </div>


    </div>
</div>
{% endblock %}

company/templates/company/detail.html
{% extends 'company/base.html' %}
{% block title %}
Detail
{% endblock %}

{% block body %}
    <p>Name: {{ company.name }}</p>
    <p>Capital: {{ company.earnings}}</p>
    <p>Parent: {{ company.parent}}</p>
{% endblock %}

company/templates/company/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

company/templates/company/index.html
{% extends 'company/base.html' %}

{% block title %}
Home
{% endblock %}

{% block body %}

{% for company in company_list %}
    <div class="list-group">
        <a href="{% url 'company:company_detail' company.pk %}" class="list-group-item">Name: {{ company.name }}
            <br>Capital: {{ company.earnings }}
            <br>Parent: {{ company.parent }}
         <form action="{% url 'company:company_edit' company.pk %}" method="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Edit</button>
         </form>

        <form action="{% url 'company:company_delete' company.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Delete</button>
        </form>
        </a>
        <br>
    </div>
{% endfor %}
{% endblock %}

company/templates/company/tree.html
{% extends 'company/base.html' %}

{% block title %}
Tree
{% endblock %}

{% block body %}
{% load mptt_tags %}
<ul>
    {% recursetree nodes %}
        <li>
            {{ node.name }} | {{ node.earnings }} |
            {% if not node.earnings == node.count_earnings %}
            {{ node.count_earnings }}
            {% endif %}
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}

        </li>
    {% endrecursetree %}
</ul>
{% endblock %}